CREATE DATABASE EventPlus;
GO

USE EventPlus;

CREATE TABLE TipoUsuario(

	IdTipoUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Titulo		  NVARCHAR (100)		   NOT NULL
);
GO

CREATE TABLE TipoEvento(
	IdTipoEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Titulo		 NVARCHAR (100)		   NOT NULL
);
GO

CREATE TABLE Instituicao(
	IdInstituicao UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Endereco	  NVARCHAR (100)		   NOT NULL,
	NomeFantasia  NVARCHAR (100)		   NOT NULL,
	CNPJ		  NVARCHAR (14)
);
GO

CREATE TABLE Usuario(
	IdUsuario UNIQUEIDENTIFIER  PRIMARY   KEY DEFAULT ((NEWID())),
	Nome	  NVARCHAR (100)		      NOT NULL,
	Email     NVARCHAR (256)	UNIQUE	  NOT NULL,
	Senha     NVARCHAR (60)		UNIQUE	  NOT NULL,

	IdTipoUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoUsuario (IdTipoUsuario)
);
GO

CREATE TABLE Evento(
	IdEvento UNIQUEIDENTIFIER  PRIMARY   KEY DEFAULT ((NEWID())),
	Nome		NVARCHAR (100)		      NOT NULL,
	DataEvento	DATETIME				  NOT NULL,
	Descricao   TEXT					  NOT NULL,

	IdTipoEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoEvento (IdTipoEvento),
	IdInstuicao  UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Instituicao (IdInstituicao)
);
GO

CREATE TABLE Presenca(
	IdPresenca UNIQUEIDENTIFIER  PRIMARY   KEY DEFAULT ((NEWID())),
	Situacao   BIT				 NOT NULL,

	IdEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Evento (IdEvento),
	IdUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario (IdUsuario)
);
GO

CREATE TABLE ComentarioEvento(
	IdComentarioEvento UNIQUEIDENTIFIER  PRIMARY   KEY DEFAULT ((NEWID())),
	DataComentarioEvento				 DATETIME  NOT NULL,
	Descricao		   NVARCHAR	(200)	 NOT NULL,
	Exibe			   BIT				 NOT NULL,
	
	IdEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Evento (IdEvento),
	IdUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario (IdUsuario)
);
GO