CREATE DATABASE ConnectPlus;
GO

USE ConnectPlus;

CREATE TABLE TipoContato(

	IdTipoContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Titulo NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE Contato(

	IdContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Nome NVARCHAR(100) NOT NULL,
	DadosContato VARCHAR(100),
	Imagem NVARCHAR(100),

	IdTipoContato UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoContato(IdTipoContato)

);